[[items]]
from = "./dragon-verse/JavaScripts/util/GToolkit.ts"
to = ["./pet-simulator/JavaScripts/utils/GToolkit.ts", "./battleworld/JavaScripts/utils/GToolkit.ts"]

[[items]]
from = "./dragon-verse/JavaScripts/util/README.md"
to = ["./pet-simulator/JavaScripts/utils/README.md","./battleworld/JavaScripts/utils/README.md"]

[[items]]
from = "./dragon-verse/JavaScripts/controller/key-operation-manager"
to = ["./pet-simulator/JavaScripts/controller/key-operation-manager", "./battleworld/JavaScripts/controller/key-operation-manager"]