POST https://mw-http-api.gpark.io/externalRouter/sso/universal/user/v1/get/temp/token
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjA5NzI1OSIsImlzcyI6Im1ldGF3b3JsZCIsImV4cCI6MTcxMDQ4OTUzOCwiaWF0IjoxNzA5Mjc5OTM4LCJ1dWlkIjoiYjc3NDRlN2NkYmExNDRlMTlhMTc2NDM5ZDY1ZjUxNDAifQ.rbEDwkgfZiXc6IKGXmhVcIvaR6RFPDJBXPNo0S2I--8

{}

###
GET https://openapi-api.gpark.io/sso/universal/user/v1/get/p12/wallet/temp/token?tempToken=RRMRDz3ASsP95soJRicHqksYe4V5SvFzCQJPRWFiGs+H4BYQtnlwy6iG1BeejqC/qKcvpN8eQXrl2lpvv19NWg==

###


###
POST https://accountapi.mobox.io/oauth/gpark
Content-Type: application/json

{
  "gtoken": "YuC+JSaf+r6SVS5qihSTPnH4vVKilgkxmHgndyKUuLMpkQptF7XDgrANZpcMmxgWqKcvpN8eQXrl2lpvv19NWg=="
}

###

POST http://16.163.58.210:8088/oauth/gpark?gtoken=tUbggp3RaqcDmFWEPYCOQ/M9DAkkF8XfruUvEUSSHxM=

